### ISSUE TITLE
Review track model properties

### ISSUE THREAD

**Issue by nickpalenchar** [nickpalenchar/spin-mix#15]

**Comment by nickpalenchar** [comment]
I'm thinking `artist` should be a string, rather than an array. I get the idea that there can be multiple artists, but because meta-data is inconsistent, I'm not sure there would be a good way to parse each artists and push them to an array.

**Comment by nickpalenchar** [comment]
add `btm` and `time` to the model?

**Comment by emches** [comment]
@nickpalenchar I changed artist to string and the model now looks like this:

```
  name: { type: String, required: true, trim: true },
  artist: { type: String, required: true, trim: true },
  genre: [String],
  extension: { type: String },
  path: {type: String},
  bpm: {type: Number},
  key: {type: String},
  comment: {type: String},
  cover: {type: Buffer, select: false },
  duration: {type: Number}
```

Will push in a few so you guys can take a look
