### ISSUE TITLE
need to find a way to add duplicates

### ISSUE THREAD

**Issue by nickpalenchar** [nickpalenchar/spin-mix#37]

**Comment by nickpalenchar** [comment]
Adding a song to the mix pushed the song object to the mix array. This is rendered via  `ng-repeat` iterating through said array. However, duplicates are not allowed in `ng-repeat`. will need to find a way to create a "copy" of the song and then add it  to the array.

I can do this myself, but if anyone has a preference or a need as to how this should be done please let me know

**Comment by aMattBryan** [comment]
you can `track by track._id`, which makes the basis for determining whether an element is a duplicate the _id... which of course will always be unique.

**Comment by MattBry** [comment]
it's ugly, but you can add a randomly-generated pseudoId property to each track added to the `$scope.mix` and `track by track.pseudoId`.
