### ISSUE TITLE
refactor MixboardController functions into Factories

### ISSUE THREAD

**Issue by nickpalenchar** [nickpalenchar/spin-mix#43]

**Comment by nickpalenchar** [comment]
`MixBoardController` is growing in size. Might be a good idea to start refactoring into a factories that returns objects of multiple functions. I will discuss more about this during scrum tomorrow

**Comment by MattBry** [comment]
I did the mix-add and -reorder functions, but I'm too scared to touch @emches 's $scope.prevWave
